#!/usr/bin/env bash

set -e # halt script on error

bundle exec jekyll build

bundle exec htmlproofer \
  --assume-extension \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --url-ignore 'https://github.com/sd17fall/ReadingJournal-myname,https://en.wikipedia.org/wiki/De_Morgan&#39;s_laws' \
  "$@" \
  ./_site

# External links are ignored for the following reasons:
# - https://github.com/sd17fall/ReadingJournal-myname is an example
# - https://en.wikipedia.org/wiki/De_Morgan&#39;s_laws nbconvert quotes this but it works
